runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/ampleclogic/index.html
  upload: dist/ampleclogic/index.html

skip_files:
- e2e/
- node_modules/
- src/
- coverage
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^LICENSE
