steps:
# Install node packages
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  
# Build productive files
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--prod']
  
# Deploy to Google Cloud App Engine
- name: 'gcr.io/cloud-builders/npm'
  args: ['app', 'deploy', '--version=prod', '--bucket=democicdangular-staging']

